<?php

namespace Linkorb\Ace;

class AceEditorMode
{
    protected $modeArray = [
        'abap' => 'ABAP',
        'abc' => 'ABC',
        'as' => 'ActionScript',
        'ada|adb' => 'ADA',
        '^htaccess|^htgroups|^htpasswd|^conf|htaccess|htgroups|htpasswd' => 'Apache_Conf',
        'asciidoc|adoc' => 'AsciiDoc',
        'dsl|asl' => 'ASL',
        'asm|a' => 'Assembly_x86',
        'ahk' => 'AutoHotKey',
        'bat|cmd' => 'BatchFile',
        'bro' => 'Bro',
        'cpp|c|cc|cxx|h|hh|hpp|ino' => 'C_Cpp',
        'c9search_results' => 'C9Search',
        'cirru|cr' => 'Cirru',
        'clj|cljs' => 'Clojure',
        'CBL|COB' => 'Cobol',
        'coffee|cf|cson|^Cakefile' => 'coffee',
        'cfm' => 'ColdFusion',
        'cs' => 'CSharp',
        'csd' => 'Csound_Document',
        'orc' => 'Csound_Orchestra',
        'sco' => 'Csound_Score',
        'css' => 'CSS',
        'curly' => 'Curly',
        'd|di' => 'D',
        'dart' => 'Dart',
        'diff|patch' => 'Diff',
        '^Dockerfile' => 'Dockerfile',
        'dot' => 'Dot',
        'drl' => 'Drools',
        'edi' => 'Edifact',
        'e|ge' => 'Eiffel',
        'ejs' => 'EJS',
        'ex|exs' => 'Elixir',
        'elm' => 'Elm',
        'erl|hrl' => 'Erlang',
        'frt|fs|ldr|fth|4th' => 'Forth',
        'f|f90' => 'Fortran',
        'fsi|fs|ml|mli|fsx|fsscript' => 'FSharp',
        'ftl' => 'FTL',
        'gcode' => 'Gcode',
        'feature' => 'Gherkin',
        '^.gitignore' => 'Gitignore',
        'glsl|frag|vert' => 'Glsl',
        'gbs' => 'Gobstones',
        'go' => 'golang',
        'gql' => 'GraphQLSchema',
        'groovy' => 'Groovy',
        'haml' => 'HAML',
        'hbs|handlebars|tpl|mustache' => 'Handlebars',
        'hs' => 'Haskell',
        'cabal' => 'Haskell_Cabal',
        'hx' => 'haXe',
        'hjson' => 'Hjson',
        'html|htm|xhtml|vue|we|wpy' => 'HTML',
        'eex|html.eex' => 'HTML_Elixir',
        'erb|rhtml|html.erb' => 'HTML_Ruby',
        'ini|conf|cfg|prefs' => 'INI',
        'io' => 'Io',
        'jack' => 'Jack',
        'jade|pug' => 'Jade',
        'java' => 'Java',
        'js|jsm|jsx' => 'JavaScript',
        'json' => 'JSON',
        'jq' => 'JSONiq',
        'jsp' => 'JSP',
        'jssm|jssm_state' => 'JSSM',
        'jsx' => 'JSX',
        'jl' => 'Julia',
        'kt|kts' => 'Kotlin',
        'tex|latex|ltx|bib' => 'LaTeX',
        'less' => 'LESS',
        'liquid' => 'Liquid',
        'lisp' => 'Lisp',
        'ls' => 'LiveScript',
        'logic|lql' => 'LogiQL',
        'lsl' => 'LSL',
        'lua' => 'Lua',
        'lp' => 'LuaPage',
        'lucene' => 'Lucene',
        '^Makefile|^GNUmakefile|^makefile|^OCamlMakefile|make' => 'Makefile',
        'md|markdown' => 'Markdown',
        'mask' => 'Mask',
        'matlab' => 'MATLAB',
        'mz' => 'Maze',
        'mel' => 'MEL',
        'mixal' => 'MIXAL',
        'mc|mush' => 'MUSHCode',
        'mysql' => 'MySQL',
        'nix' => 'Nix',
        'nsi|nsh' => 'NSIS',
        'm|mm' => 'ObjectiveC',
        'ml|mli' => 'OCaml',
        'pas|p' => 'Pascal',
        'pl|pm' => 'Perl',
        'pgsql' => 'pgSQL',
        'blade.php' => 'PHP_Laravel_blade',
        'php|phtml|shtml|php3|php4|php5|phps|phpt|aw|ctp|module' => 'PHP',
        'epp|pp' => 'Puppet',
        'pig' => 'Pig',
        'ps1' => 'Powershell',
        'praat|praatscript|psc|proc' => 'Praat',
        'plg|prolog' => 'Prolog',
        'properties' => 'Properties',
        'proto' => 'Protobuf',
        'py' => 'Python',
        'r' => 'R',
        'cshtml|asp' => 'Razor',
        'Rd' => 'RDoc',
        'red|reds' => 'Red',
        'Rhtml' => 'RHTML',
        'rst' => 'RST',
        'rb|ru|gemspec|rake|^Guardfile|^Rakefile|^Gemfile' => 'Ruby',
        'rs' => 'Rust',
        'sass' => 'SASS',
        'scad' => 'SCAD',
        'scala' => 'Scala',
        'scm|sm|rkt|oak|scheme' => 'Scheme',
        'scss' => 'SCSS',
        'sh|bash|^.bashrc' => 'SH',
        'sjs' => 'SJS',
        'slim|skim' => 'Slim',
        'smarty|tpl' => 'Smarty',
        'snippets' => 'snippets',
        'soy' => 'Soy_Template',
        'space' => 'Space',
        'sql' => 'SQL',
        'sqlserver' => 'SQLServer',
        'styl|stylus' => 'Stylus',
        'svg' => 'SVG',
        'swift' => 'Swift',
        'tcl' => 'Tcl',
        'tf' | 'tfvars' | 'terragrunt' => 'Terraform',
        'tex' => 'Tex',
        'txt' => 'Text',
        'textile' => 'Textile',
        'toml' => 'Toml',
        'tsx' => 'TSX',
        'twig|swig' => 'Twig',
        'ts|typescript|str' => 'Typescript',
        'vala' => 'Vala',
        'vbs|vb' => 'VBScript',
        'vm' => 'Velocity',
        'v|vh|sv|svh' => 'Verilog',
        'vhd|vhdl' => 'VHDL',
        'wlk|wpgm|wtest' => 'Wollok',
        'xml|rdf|rss|wsdl|xslt|atom|mathml|mml|xul|xbl|xaml' => 'XML',
        'xq' => 'XQuery',
        'yaml|yml' => 'YAML',
    ];

    public function getAceMode($ext)
    {
        $mode = '';
        foreach ($this->modeArray as $key => $val) {
            $arr = explode('|', $key);
            if (in_array($ext, $arr)) {
                $mode = $val;
                break;
            }
        }

        return  strtolower($mode);
    }
}
